### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by minnesotaNyst** [minnesotaNyst/pm-beta#22]
At some point we need to create a :root element in the css file for our color palate. 

Currently we are using three different colors:

#2e2e31 - PRIMARY
#dc9413- SECONDARY
whitesmoke - TEXT ON BUTTONS
#55565c - BUTTON FOCUS (after click)

**Comment by anthonypotts** [comment]
I added the :root element to the css file with primary, secondary, tertiary, and quaternary color properties. Could make it more efficient in future.
